apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: slow
  namespace : kubeflow
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-standard
  fstype: ext4
  replication-type: none
reclaimPolicy: Retain

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: ddsm-vol
  namespace : kubeflow
spec:
  storageClassName: slow
  capacity:
    storage: 50G
  accessModes:
    - ReadWriteOnce
  claimRef:
    namespace: kubeflow
    name: ddsm-pvc
  gcePersistentDisk:
    pdName: ddsm
    fsType: ext4
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ddsm-pvc
  namespace : kubeflow
spec:
  storageClassName: slow
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50G
