apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"katib-controller","app.kubernetes.io/component":"katib","app.kubernetes.io/instance":"katib-controller-0.8.0","app.kubernetes.io/managed-by":"kfctl","app.kubernetes.io/name":"katib-controller","app.kubernetes.io/part-of":"kubeflow","app.kubernetes.io/version":"0.8.0"},"name":"katib-controller","namespace":"kubeflow"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"katib-controller","app.kubernetes.io/component":"katib","app.kubernetes.io/instance":"katib-controller-0.8.0","app.kubernetes.io/managed-by":"kfctl","app.kubernetes.io/name":"katib-controller","app.kubernetes.io/part-of":"kubeflow","app.kubernetes.io/version":"0.8.0"}},"template":{"metadata":{"annotations":{"prometheus.io/scrape":"true","sidecar.istio.io/inject":"false"},"labels":{"app":"katib-controller","app.kubernetes.io/component":"katib","app.kubernetes.io/instance":"katib-controller-0.8.0","app.kubernetes.io/managed-by":"kfctl","app.kubernetes.io/name":"katib-controller","app.kubernetes.io/part-of":"kubeflow","app.kubernetes.io/version":"0.8.0"}},"spec":{"containers":[{"args":["--webhook-port=8443"],"command":["./katib-controller"],"env":[{"name":"KATIB_CORE_NAMESPACE","valueFrom":{"fieldRef":{"fieldPath":"metadata.namespace"}}}],"image":"gcr.io/kubeflow-images-public/katib/v1alpha3/katib-controller:v0.8.0","imagePullPolicy":"IfNotPresent","name":"katib-controller","ports":[{"containerPort":8443,"name":"webhook","protocol":"TCP"},{"containerPort":8080,"name":"metrics","protocol":"TCP"}],"volumeMounts":[{"mountPath":"/tmp/cert","name":"cert","readOnly":true}]}],"serviceAccountName":"katib-controller","volumes":[{"name":"cert","secret":{"defaultMode":420,"secretName":"katib-controller"}}]}}}}
  creationTimestamp: "2020-06-03T02:01:54Z"
  generation: 1
  labels:
    app: katib-controller
    app.kubernetes.io/component: katib
    app.kubernetes.io/instance: katib-controller-0.8.0
    app.kubernetes.io/managed-by: kfctl
    app.kubernetes.io/name: katib-controller
    app.kubernetes.io/part-of: kubeflow
    app.kubernetes.io/version: 0.8.0
  name: katib-controller
  namespace: kubeflow
  ownerReferences:
  - apiVersion: app.k8s.io/v1beta1
    blockOwnerDeletion: true
    controller: false
    kind: Application
    name: katib-controller
    uid: 32eb4ba9-a53e-11ea-b2c8-42010a800168
  resourceVersion: "3525664"
  selfLink: /apis/extensions/v1beta1/namespaces/kubeflow/deployments/katib-controller
  uid: 3286f918-a53e-11ea-b2c8-42010a800168
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: katib-controller
      app.kubernetes.io/component: katib
      app.kubernetes.io/instance: katib-controller-0.8.0
      app.kubernetes.io/managed-by: kfctl
      app.kubernetes.io/name: katib-controller
      app.kubernetes.io/part-of: kubeflow
      app.kubernetes.io/version: 0.8.0
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        sidecar.istio.io/inject: "false"
      creationTimestamp: null
      labels:
        app: katib-controller
        app.kubernetes.io/component: katib
        app.kubernetes.io/instance: katib-controller-0.8.0
        app.kubernetes.io/managed-by: kfctl
        app.kubernetes.io/name: katib-controller
        app.kubernetes.io/part-of: kubeflow
        app.kubernetes.io/version: 0.8.0
    spec:
      containers:
      - args:
        - --webhook-port=8443
        command:
        - ./katib-controller
        env:
        - name: KATIB_CORE_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        image: gcr.io/kubeflow-images-public/katib/v1alpha3/katib-controller:v0.8.0
        imagePullPolicy: IfNotPresent
        name: katib-controller
        ports:
        - containerPort: 8443
          name: webhook
          protocol: TCP
        - containerPort: 8080
          name: metrics
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /tmp/cert
          name: cert
          readOnly: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: katib-controller
      serviceAccountName: katib-controller
      terminationGracePeriodSeconds: 30
      volumes:
      - name: cert
        secret:
          defaultMode: 420
          secretName: katib-controller
status:
  conditions:
  - lastTransitionTime: "2020-06-03T02:01:54Z"
    lastUpdateTime: "2020-06-03T02:03:54Z"
    message: ReplicaSet "katib-controller-6b789b6cb5" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2020-06-07T05:40:52Z"
    lastUpdateTime: "2020-06-07T05:40:52Z"
    message: Deployment does not have minimum availability.
    reason: MinimumReplicasUnavailable
    status: "False"
    type: Available
  observedGeneration: 1
  replicas: 1
  unavailableReplicas: 1
  updatedReplicas: 1
