apiVersion: "kubeflow.org/v1alpha3"
kind: Experiment
metadata:
  namespace: kubeflow-avrastog
  name: tfjob-example
spec:
  parallelTrialCount: 3
  maxTrialCount: 12
  maxFailedTrialCount: 3
  objective:
    type: maximize
    goal: 0.99
    objectiveMetricName: accuracy
  algorithm:
    algorithmName: random
  parameters:
    - name: --learning_rate
      parameterType: double
      feasibleSpace:
        min: "0.002"
        max: "0.005"
    - name: --batch_size
      parameterType: discrete
      feasibleSpace:
        list: ["512", "1024", "2048"]
  trialTemplate:
    goTemplate:
        rawTemplate: |-
          apiVersion: "kubeflow.org/v1"
          kind: TFJob
          metadata:
            name: {{.Trial}}
            namespace: {{.NameSpace}}
          spec:
           tfReplicaSpecs:
            Worker:
              replicas: 1 
              restartPolicy: OnFailure
              template:
                spec:
                  volumes: 
                    - name: mnist-storage
                      persistentVolumeClaim:
                        claimName: mnist-pvc
                  containers:
                    - name: tensorflow 
                      image: gcr.io/dais-data-dev-txwj/mnist/train_pvc:latest
                      imagePullPolicy: Always
                      command:
                        - "python"
                        - "/train.py"
                        - "--epoch 1 "
                        - "--save_model 0"
                        {{- with .HyperParameters}}
                        {{- range .}}
                        - "{{.Name}}={{.Value}}"
                        {{- end}}
                        {{- end}}
                      volumeMounts:
                        - mountPath: "/mnt/mnist"
                          name: mnist-storage
