steps:
# This step runs the unit tests on the app
- name: 'python:3.7-slim'
  id: CompilePipleline
  entrypoint: /bin/sh
  args:
  - '-c'
  - 'pip install -r requirements.txt --upgrade && python pipeline.py'
