steps:
- name: python:3.7
  id: INSTALL
  entrypoint: python3
  args:
  - '-m'
  - 'pip'
  - 'install'
  - '-t'
  - '.'
  - '-r'
  - 'train/requirements.txt'
- name: python:3.7
  entrypoint: 'bash'
  id: RUN-UNIT-TESTS
  args:
  - '-c'
  - |
    coverage run --source=train -m nose2 -v -s test && coverage report train/train.py
  waitFor:
  - INSTALL
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    docker pull gcr.io/$PROJECT_ID/mnist/train:latest || exit 0
  waitFor:
  - RUN-UNIT-TESTS-AND-COVERAGE
- name: 'gcr.io/cloud-builders/docker'
  args: 
  - 'build'
  - '-t'
  - 'gcr.io/$PROJECT_ID/mnist/train:latest'
  - '--cache-from'
  - 'gcr.io/$PROJECT_ID/mnist/train:latest'
  - 'train/'
images: ['gcr.io/$PROJECT_ID/mnist/train:latest']
